### ISSUE TITLE
Make parameter name always work

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#138]
AWS datapipeline shows the following error when the letter after my is in lower case

    ERROR: Parameter id must have prefix 'my'

e.g. it works with `myAwsParam`, but it gives above error if it is `myawsParam` it will give the above un-helpful message.

We should either alert before submit pipeline, or automatically change the lower case to upper case automatically

**Comment by sethyates** [comment]
I think it supports my_ with the underscore so we should try that.

**Comment by realstraw** [comment]
Ah, cool. Then I'll be an easy fix. I'll try that
