### ISSUE TITLE
Better/templated SNS alarm support

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#160]
Current alarm message requires special syntax such as `#{node.@status}` and `#{node.name}`. I think we can provide standard or custom alarm templates which hides the details, and allows better and easier alarm.

**Comment by sethyates** [comment]
I think one thing would be to have something like we have with the `format` in `DateTimeFunctions`, perhaps a `node` object with `status` and `name` properties which return these format strings.

```
class RuntimeNodeInfo {
  def name = "#{node.name}"
  def status = "#{node.@status}"
}

// Somewhere, possibly in DataPipelineDef?
val node = RuntimeNodeInfo()
```

**Comment by sethyates** [comment]
That's probably not the whole solution, but would help the current formats.  Also, perhaps a set of canned formats would be good.
