### ISSUE TITLE
Failures when activities not using `named`

### ISSUE THREAD

**Issue by sethyates** [krux/hyperion#202]
With the new `WorkflowGraph`, several pipelines that don't use `named` are failing to generate due to assertion.

**Comment by sethyates** [comment]
Seems to be related to `RandomizedObjectId` generating a new random ID on `copy`, so if you're modifying or copying activities, you don't have stable ID's.

**Comment by sethyates** [comment]
I would think the same holds true for `NameGroupObjectId` unless both `named` and `groupedBy` were specified.

**Comment by sethyates** [comment]
````
  "RandomizedObjectId" should {
    "generate a stable id" in {
      val r = RandomizedObjectId("seed")
      assert(r.toString == r.copy().toString)
    }
  }

  "NameGroupObjectId" should {
    "generate a stable id with name" in {
      val n = NameGroupObjectId("name", "")
      assert(n.toString == n.copy().toString)
    }

    "generate a stable id with group" in {
      val g = NameGroupObjectId("", "g")
      assert(g.toString == g.copy().toString)
    }
  }
````

**Comment by sethyates** [comment]
All of those test cases currently fail.

**Comment by realstraw** [comment]
Do we use `id.copy()` anywhere? It seems modifying an object with id field modify `id`.

```scala
scala> case class A (id: PipelineObjectId, x: String)
defined class A

scala> val a = A(PipelineObjectId("A"), "1")
a: A = A(A_4fea06b0-9929-4588-9671-3337621d39cf,1)

scala> a.copy(x = "2")
res1: A = A(A_4fea06b0-9929-4588-9671-3337621d39cf,2)

scala> a.copy(x = "3")
res2: A = A(A_4fea06b0-9929-4588-9671-3337621d39cf,3)
```

**Comment by sethyates** [comment]
`named` and `groupedBy` both effectively copy the ID.

**Comment by sethyates** [comment]
Check my PR I just filed.  I think the cause is if for some reason the object is every copied, it's "identity" is lost as a new UUID is generated.  This is very bad for an object that is supposed to represent an identifier...

**Comment by realstraw** [comment]
but the only two methods that changes the `id` are `named` and `groupedBy`, which changes the `id` anyway.

**Comment by sethyates** [comment]
There's lots of code in WorkflowGraph that handles the id, including making it a key into a Map.  I don't know the internals, but are you sure there's not a `copy()` going on in that instance?

**Comment by realstraw** [comment]
The only thing that references `copy` is it calls `dependsOn` at the end. Unless there's some thing we did with `dependsOn`. Don't think we call `copy` on `id` though. I'll double check.

I doubt this will fix the issue, still seems like an `id` collision somewhere to me. But I would :+1: for stable `id`.

**Comment by realstraw** [comment]
It actually might be something with comparing `PipelineObjectId` and use it as key in the `Map` in `WorkflowGraph`, I bet change them all to `String` might actually fix the problem.

**Comment by realstraw** [comment]
Yes that's the problem:

```scala
scala> PipelineObjectId(Nil.getClass)
res3: com.krux.hyperion.common.RandomizedObjectId = Nil_b8223ba4-8662-4c67-9997-d0b13768712f

scala> PipelineObjectId(Nil.getClass)
res4: com.krux.hyperion.common.RandomizedObjectId = Nil_959f761a-023c-471d-8e1c-d1b3ae897bc2

scala> res3 == res4
res5: Boolean = true
```

**Comment by sethyates** [comment]
blimey

**Comment by sethyates** [comment]
well my change will fix that...

**Comment by sethyates** [comment]
the problem is that the key part of that id, the UUID isn't a property, so it isn't used for comparison.  Only "Nil" is a property so of course they are the same.

**Comment by realstraw** [comment]
Bingo :+1: :sparkles: :sparkles: :sparkles:
