### ISSUE TITLE
Inconsistent step in MapReduceActivity

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#307]
Unlike other activities that accepts `S3Uri` as a `jar`, `MapReduceActivity` in inconsistently defined as accepting only String. Need to change it to accept `S3Uri` instead.

**Comment by sethyates** [comment]
Please don't do this as it was intentional. Some jars are already on the cluster like s3distcp

**Comment by realstraw** [comment]
Ah, cool, thought it was a bug. Closing now
