### ISSUE TITLE
WorkflowGraph simplification

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#341]
The current workflow graph does not check the generated dependency graph is free of redundant dependencies (meaning `A->B->C` may generate a dependency with `A -> C`, which is not necessary)

It should by default (or have an option) to generate dependency graph free of redundant dependency.

related to: https://github.com/krux/hyperion/issues/190

**Comment by mosche** [comment]
We've recently ran into Data Pipeline errors caused by the inclusion of transitive dependencies:

```
Errors: [May only specify up to '50' fields per object]
```

Problem is simply that this can quickly explode the number of fields per object.
