### ISSUE TITLE
Enable .reduceLeft(_ ~> _) on a list of pipeline activities

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#353]
Currently it does not work, as it expect to return `PipleineActivit[_ <: ResourceObject]` instead of `WorkExpression`.

At the moment, one either need to use `.foldLeft[WorkflowExpression](WorkflowNoActivityExpression)(_ ~> _)` or `.map(x => x: WorkflowExpression).reduceLeft(_ ~> _)`. Neither looks elegant.

Be able to simply use `.reduceLeft(_ ~> _)` would be ideal.

**Comment by sethyates** [comment]
Note that `reduce*` will fail on an empty collection...

**Comment by sethyates** [comment]
With #333, you could use `.map(_.toWorkflowExpression).reduceLeft(_ ~> _)` which is marginally more elegant.

**Comment by sethyates** [comment]
Added code that allows this:

```
. toWorkflowExpression(_ ~> _)
```
