### ISSUE TITLE
Resource object should use more functional way to run activities

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#37]
Currently we enable resource to initialise an supporting activity with activity specific functions like `runSpark(args)`. Instead of this, we should use more functional way by supplying only a `run(act: (ResourceObject) => PipelineActivity)` function so that all subsequent activity that runs on the resource can be supported automatically.

This depends on #17

**Comment by sethyates** [comment]
This should be fixed by #36.

**Comment by sethyates** [comment]
This would be easy if we used implicits for the resources, like so:
```
val workflow = Ec2Resource().run { implicit ec2 =>
  val activity1 = JarActivity(someJar)
  val activity2 = JarActivity(someOtherJar)
  activity1 :~> activity2
}
```

**Comment by sethyates** [comment]
See: #126

**Comment by sethyates** [comment]
Do we still need this?

**Comment by realstraw** [comment]
No, I'm closing it
