### ISSUE TITLE
EmrCluster.standardBootstrapAction is not compatible with EMR-4+

### ISSUE THREAD

**Issue by bakerlee** [krux/hyperion#372]
It doesn't appear that the bootstrap action is required for an EMR cluster, so this field should be an `Option[Seq[HString]]`.

**Comment by sethyates** [comment]
Can't you just use `Seq.empty`?

**Comment by bakerlee** [comment]
My apologies, I didn't explain the issue properly. The issue is that SparkCluster overrides standardBootstrapAction with
```
override def standardBootstrapAction = 
    (s"s3://support.elasticmapreduce/spark/install-spark,-v,${sparkVersion},-x": HString) +:
    super.standardBootstrapAction
```
However, [EMR 4+ doesn't install software with bootstrap actions](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-release-differences.html#emr-installing-apps). This script _may_ not have an effect, but I'm leery to make assumptions.

I can't figure out a workaround, but I would be grateful if somebody pointed one out.

**Comment by realstraw** [comment]
There is a workaround at the moment by using a `MapReduceCluster` with a spark configuration and a custom `MapReduceStep` instead. We are planning to make SparkCluster emr release label compatible, but have not got time to do that yet. You can extend that in your own application or feel free to make a backward compatible PR. For more details see my reply in https://github.com/krux/hyperion/issues/369

**Comment by bakerlee** [comment]
Great, thanks for the quick reply and help. I will try to work on a PR in the near future.

**Comment by realstraw** [comment]
I've created a separate issue https://github.com/krux/hyperion/issues/380 for tracking the spark related work separately. Closing this one.
