### ISSUE TITLE
Implement a PgpEncryptActivity

### ISSUE THREAD

**Issue by sethyates** [krux/hyperion#374]
Using (probably) OpenPGP and BouncyCastle, implement a contrib activity to PGP encrypt a file.

**Comment by sethyates** [comment]
This should encrypt every file in the `input` and place the encrypted file separately in `output`.  Should support creating a optional `_SUCCESS` marker and filter out "hidden" input files.  Should optionally support ascii armor.

**Comment by sethyates** [comment]
Another option is using the `pgp` unix command assuming the Amazon AMI's have a reasonable version of it.

**Comment by prjasper** [comment]
I've submitted an initial implementation in this PR https://github.com/krux/hyperion/pull/426
Feedback welcome.
It supports ASCII armor of the public key (it takes either ASCII or binary automatically).
It doesn't add a _SUCCESS marker or filter out hidden files yet, but would be relatively easy to add if these are important.
It's implemented using the GNU gpg command.

**Comment by prjasper** [comment]
Now creates a _SUCCESS marker on successful encryption.
Also filters out hidden files and directories, and empty/marker files like _SUCCESS.
