### ISSUE TITLE
Implement a PgpDecryptActivity

### ISSUE THREAD

**Issue by sethyates** [krux/hyperion#375]
Using (probably) OpenPGP and BouncyCastle, implement a contrib activity to PGP decrypt a file.

**Comment by sethyates** [comment]
Another option is using the pgp unix command assuming the Amazon AMI's have a reasonable version of it.

**Comment by sethyates** [comment]
This should decrypt every non-hidden input file and produce a decrypted file in the output folder.  If an input file is not encrypted, it should be copied across untouched.  Optionally support ascii armored input and producing a _SUCCESS marker.

**Comment by prjasper** [comment]
I've submitted an initial implementation in this PR #426
Feedback welcome.
It doesn't add a _SUCCESS marker or filter out hidden files yet, but would be relatively easy to add if these are important. It doesn't copy across unencrypted files.
It's implemented using the GNU gpg command.

**Comment by prjasper** [comment]
Now creates a _SUCCESS marker on successful decryption.
Also filters out hidden files and directories, and empty/marker files like _SUCCESS.
(Still doesn't copy across unencrypted files.)
