### ISSUE TITLE
EmrClusters with multiple EmrConfiguration objects not supported

### ISSUE THREAD

**Issue by hoangelos** [krux/hyperion#376]
The Amazon CLI supports EmrClusters that have an array of EmrConfiguration objects in the JSON.  I don't see a way to do this with hyperion.

**Comment by sethyates** [comment]
The `EmrCluster` supports an `EmrConfiguration` (https://github.com/krux/hyperion/blob/master/core/src/main/scala/com/krux/hyperion/resource/EmrCluster.scala#L124).  Are you saying you'd like to have a list of these instead of a single one (they can be nested AFAIK).

**Comment by hoangelos** [comment]
EmrCluster does support one EmrConfiguration, which can be nested.  However when you do this without adding a classification, which is required, AWS errors out.  The use case is say you are configuring a Spark EMR Cluster you could overwrite hadoop-log4j, spark-metrics, spark-defaults, yard-site, etc....

**Comment by sethyates** [comment]
OK just so I'm clear, the "ask" is to support a `Seq[EmrConfiguration]` instead of `Option[EmrConfiguration]`?

**Comment by hoangelos** [comment]
I've updated a Pull Request as per the Contributor.

**Comment by hoangelos** [comment]
I updated, does the pull request auto update or do I need to reinstate it?

**Comment by hoangelos** [comment]
I also tested this with our code, and this patch fixes the problem for us.

**Comment by hoangelos** [comment]
I noticed on the merge that the version wasn't change in build.sbt is that intention?

**Comment by sethyates** [comment]
No.  Fixed now.
