### ISSUE TITLE
Cannot override DefaultObject

### ISSUE THREAD

**Issue by sethyates** [krux/hyperion#379]
Currently, `DefaultObject` is a case class with a schedule and a hard-coded map.  This makes it impossible to override even though it is declared as `def defaultObject: DefaultObject` in `DataPipelineDef`.

**Comment by bakerlee** [comment]
Not sure if it belongs under here or a separate issue, but can hyperion.log.uri be made optional? DefaultObject.pipelineLogUri is optional for Data Pipeline.

**Comment by realstraw** [comment]
Don't think it is required, we could make a separate issue for making the LogUri optional, as it is a much simpler change.

**Comment by bakerlee** [comment]
Ok, created #388. I'll probably be able to submit a pull request soon.

**Comment by realstraw** [comment]
Great! Thank you!
