### ISSUE TITLE
No support for securityGroupIds in Ec2Resource

### ISSUE THREAD

**Issue by gtitievsky** [krux/hyperion#398]
While AWS Data Pipeline has support for securityGroupIds in Ec2Resource (http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-ec2resource.html), hyperion doesn't provide that functionality. This functionality is required if one uses VPC.

**Comment by sethyates** [comment]
Why does .withSecurityGroupIds on Ec2Resource not work for you?

**Comment by gtitievsky** [comment]
because I do not specify security group, but it's required. See this exception:
[error] Exception in thread "main" java.lang.ExceptionInInitializerError
[error]         at com.here.probe.ingestion.pipeline.ContinuousIngestionPipeline.main(ContinuousIngestionPipeline.scala)
[error] Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'hyperion.aws.ec2.securitygroup'
[error]         at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
[error]         at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
[error]         at com.krux.hyperion.HyperionContext.ec2SecurityGroup$lzycompute(HyperionContext.scala:37)
[error]         at com.krux.hyperion.HyperionContext.ec2SecurityGroup(HyperionContext.scala:37)
[error]         at com.krux.hyperion.resource.Ec2Resource$.apply(Ec2Resource.scala:72)

**Comment by gtitievsky** [comment]
I'm about to make some changes to my forked branch and, hopefully, create a pull request
