### ISSUE TITLE
DependsOn is not supported for activities (it's private in hyperion)

### ISSUE THREAD

**Issue by gtitievsky** [krux/hyperion#405]
Our use case involves having a precondition on an activity that should run after another activity is run. This is only possible if one activity is dependent on the other (ie uses dependsOn functionality as described in [here](http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-shellcommandactivity.html#d0e19569) )

Currently the dependsOn def in [PipelineActivity.scala](https://github.com/krux/hyperion/blob/29df5bd846716dc6c977a34e072fb4790f3ae877/core/src/main/scala/com/krux/hyperion/activity/PipelineActivity.scala) is marked _private[hyperion]_ , thus disabling this functionality

**Comment by realstraw** [comment]
activity dependencies are specified by the workflow expressions. e.g. `act1 ~> act2` will make `act2` depend on `act1`. See https://github.com/krux/hyperion/blob/master/examples/src/main/scala/com/krux/hyperion/examples/ExampleWorkflow.scala#L40 and https://github.com/krux/hyperion/blob/master/examples/src/main/scala/com/krux/hyperion/examples/ExampleSpark.scala

**Comment by gtitievsky** [comment]
I understand. I thought that dependsOn would solve the following problems.
I have the following snippet of code:

InstallScalaActivity(doAlarms, configuration)(nanoInstance) ~>
        NanoClusterActivity()(nanoInstance)
          .withMaximumRetries(0)
          .whenMet(
            CheckAllHoursExistPrecondition(sourceBaseUri,
ScheduledStartTime, ScheduledEndTime, configuration, doAlarms))


However, inside the pipeline, the CheckAllHoursExistPrecondition is
executed prior to InstallScalaActivity. I thought that dependsOn parameter
would resolve that issue. At least that's what I deduced from this:
https://forums.aws.amazon.com/thread.jspa?threadID=217354

Currently, I have no choice but to convert the
CheckAllHoursExistPrecondition into a standalone activity.

Let me know what you think
-gt

**Comment by realstraw** [comment]
I'm not sure what the aws forum solution suggests (a bit ambiguous). It seems, to me, that aws suggests moving the precondition to the first activity, which is not your case. So far, the expression should already generates the correct activity dependencies (i.e. `NanoClusterActivity.dependsOn(InstallScalaActivity)`).

It seems you want to have `CheckAllHoursExistPrecondition` dependsOn `InstallScalaActivity`. But I don't see `dependsOn` available for preconditions (at least not from aws documentation). You might want to play with the pipeline in data pipeline's architect view or even the raw json to find workarounds/undocumented features then we could find ways to put in Hyperion.

**Comment by gtitievsky** [comment]
good point. I'll try in my spare time. Meanwhile, I'll just make my
precondition an activity.
-gt

**Comment by sethyates** [comment]
This seems to be better executed using dependencies between activities rather than a precondition.
