### ISSUE TITLE
SparkStep and SparkTaskActivity needs to be able to pass a HdfsUri to withArguments()

### ISSUE THREAD

**Issue by hoangelos** [krux/hyperion#416]
There doesn't seem to be a way to pass a HdfsUri location to wtihArguments.  HdfsUri needs to be able to be converted to HString.

**Comment by realstraw** [comment]
Which `withArguments` are you talking about? `HdfsUri` was added later as a quick fix mainly to support hdfs in s3-dist-cp activity. So it may not have the best design or fully coverage to everything.

**Comment by hoangelos** [comment]
We use Hdfs in our EMR jobs too, and would rather use types than strings.  CommandRunnerStep has a function withArguments, that we pass S3Uri to and it seems to work fine, because of the implicit that change them into HS3Uri.  I'm working on a patch to this.

**Comment by hoangelos** [comment]
Reopened after fixing the description.
