### ISSUE TITLE
SparkTaskActivity failing in 4.x.x

### ISSUE THREAD

**Issue by hoangelos** [krux/hyperion#441]
Apparently, when using HadoopActivity, which the SparkTaskActivity uses, is complaining that command-runner.jar should be a URI from S3 or a local file.  It is a local file, so not sure if this is a bug in AWS or not.  But we could try to put the full path to command-runner.jar.  This wasn't surfaced before because the old version uses s3 location for this script.

Work around: Use SparkActivity with SparkStep(s) instead.

**Comment by sethyates** [comment]
You mean `SparkTaskActivity`?

**Comment by hoangelos** [comment]
Yes and I ironically broke it :-/
