### ISSUE TITLE
Implement a dependency graph DSL to be returned by workflow in PipelineDef

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#59]
Instead of returning the activity that is the last one in the dependency graph, design and implement a DSL that connects all activities together at the end for dependencies.
e.g. instead of having
```scala
def workflow = {
  val a1 = Activity1()
  val a2 = Activity2().dependsOn(a1)
  val a3 = Activity3().dependsOn(a1)
  val a4 = Activity4().dependsOn(a2, a3)

  Some(a4)
}
```
change it to something like:
```scala
def workflow = {
  val a1 = Activity1()
  val a2 = Activity2()
  val a3 = Activity3()
  val a4 = Activity4()
  
  a1 ~> a2,
        a3 ~> a4
}
```

**Comment by sethyates** [comment]
+1

although I think the example isn't quite right.  It looks like a1 is dependent on a2.  Based on refactoring the original, I'd have the DSL something like:
````
  val a1 = Activity1()
  val a2 = Activity2().dependsOn(a1)
  val a3 = Activity3().dependsOn(a1)
  val a4 = Activity4().dependsOn(a2, a3)

a4 ~> (a2 ~> a1 :: a3 ~> a1)
````

Another example:
````
  val a1 = Activity1()
  val a2 = Activity2()

a1 :: a2
````

Another example:
````
  val a1 = Activity1()
  val a2 = Activity2().dependsOn(a1)
  val a3 = Activity3().dependsOn(a2)
  val a4 = Activity4().dependsOn(a3)

a4 ~> a3 ~> a2 ~> a1
````
Based on this usage, `~>` could almost be a simple alias for dependsOn.  Main problem is it should probably be right associative, so it might need to be something like `:~>` (yuck).

**Comment by realstraw** [comment]
My thinking is that it's more natural to think of running order instead of dependencies directly. Hence the notation of
```scala
  // reads run a1, then a2 and a3 in parallel, then a4
  a1 ~> a2,
        a3 ~> a4
```
```scala
  // reads run a1 then a2 then a3 then a4
  a1 ~> a2 ~> a3 ~ a4
```
